apiVersion: v1
kind: Secret
metadata:
  name: kube-prometheus-stack-additional-scrape-configs
  namespace: monitoring
type: Opaque
stringData:
  additional-scrape-configs.yaml: |
    - job_name: external-node-exporter
      metrics_path: /metrics
      static_configs:
        - targets:
            - 192.168.1.31:9100
          labels:
            hostname: gateway
      relabel_configs:
        - source_labels: [__address__]
          regex: "(.*):9100"
          target_label: instance
          replacement: "$1"
        - target_label: job
          replacement: node-exporter
    - job_name: exchangerate-exporter
      metrics_path: /metrics
      static_configs:
        - targets:
            - exchangerate-exporter.exchangerate-exporter.svc.cluster.local:9110
    - job_name: haproxy
      metrics_path: /metrics
      basic_auth:
        username: "<path:secret/data/gateway/haproxy#user>"
        password: "<path:secret/data/gateway/haproxy#password>"
      static_configs:
        - targets:
            - 192.168.1.32:8405
    - job_name: 'temperature-exporter'
      metrics_path: '/metrics'
      static_configs:
        - targets:
          - node1:8000
          - node2:8000
          - node3:8000
          - node4:8000
          - node5:8000
          - node6:8000
          - node7:8000
          - node8:8000
      relabel_configs:
      - source_labels: [__address__]
        regex: '(.*):8000'
        target_label: instance
        replacement: '$1'
    - job_name: 'etcd-exporter'
      metrics_path: '/metrics'
      static_configs:
        - targets:
          - node1:2381
          labels:
            node: cp-1
        - targets:
          - node2:2381
          labels:
            node: cp-2
        - targets:
          - node3:2381
          labels:
            node: cp-3 
      relabel_configs:
      - source_labels: [__address__]
        regex: '(.*):2381'
        target_label: instance
        replacement: '$1'
  