apiVersion: v1
kind: Secret
metadata:
  name: kube-prometheus-stack-additional-scrape-configs
  namespace: monitoring
type: Opaque
stringData:
  additional-scrape-configs.yaml: |
    - job_name: external-prometheus
      static_configs:
        - targets:
            - monitoring-backend-prometheus-db01-001:9090

    - job_name: external-node-exporter
      metrics_path: /metrics
      static_configs:
        - targets:
            - 192.168.1.31:9100
      relabel_configs:
        - source_labels: [__address__]
          regex: "(.*):9100"
          target_label: instance
          replacement: "$1"
        - target_label: job
          replacement: node-exporter

    - job_name: exchangerate-exporter
      metrics_path: /metrics
      static_configs:
        - targets:
            - exchangerate-exporter.exchangerate-exporter.svc.cluster.local:9110

    - job_name: haproxy
      metrics_path: /metrics
      basic_auth:
        username: "<path:secret/data/gateway/haproxy#user>"
        password: "<path:secret/data/gateway/haproxy#password>"
      static_configs:
        - targets:
            - 192.168.1.32:8405
