apiVersion: v1
kind: Secret
metadata:
  name: kube-prometheus-stack-alertmanager-config
  namespace: monitoring
type: Opaque
stringData:
  alertmanager.yaml: |
    global:
      resolve_timeout: 5m
      slack_api_url: "<path:secret/data/monitoring-k8s/credential#token-slack>"

    route:
      group_by:
        - alertname
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 3h
      receiver: slack

    receivers:
      - name: slack
        slack_configs:
          - channel: "#prometheus-alert"
            title: >-
              {{ if eq $.Status "firing" }}🔥 Firing{{ else }}✅ Resolved{{ end }}:
              {{ .CommonLabels.alertname }}
            text: |-
              {{ range .Alerts }}
              startsAt: {{ .StartsAt | tz "Asia/Tokyo" | date "2006-01-02 15:04:05 MST" }}
              {{- with .Annotations.expr }}
              expr: {{ . }}
              {{- end }}
              explore: <{{ .GeneratorURL }}|Open in Grafana Explore>
              summary: {{ .Annotations.summary }}
              description: {{ .Annotations.description }}
              status: {{ .Status }}
              ---
              {{ end }}
            send_resolved: true
