apiVersion: v1
kind: Secret
metadata:
  name: kube-prometheus-stack-grafana-admin
  namespace: monitoring
type: Opaque
stringData:
  admin-user: "<path:secret/data/monitoring/grafana#user>"
  admin-password: "<path:secret/data/monitoring/grafana#password>"
