helmCharts:
  - name: kube-prometheus-stack
    repo: oci://ghcr.io/prometheus-community/charts
    version: "87.14.0"
    namespace: monitoring
    releaseName: kube-prometheus-stack
    includeCRDs: true
    valuesFile: values.yaml
