helmCharts:
  - name: kube-prometheus-stack
    repo: oci://ghcr.io/prometheus-community/charts
    version: "87.14.0"
    namespace: monitoring
    releaseName: kube-prometheus-stack
    includeCRDs: true
    valuesFile: values.yaml
  - name: prometheus-blackbox-exporter
    repo: oci://ghcr.io/prometheus-community/charts
    version: "11.15.1"
    namespace: monitoring
    releaseName: prometheus-blackbox-exporter
    valuesFile: blackbox-values.yaml

resources:
  - alertmanager-config-secret.yaml
  - additional-scrape-configs-secret.yaml
  - grafana-admin-secret.yaml
  - blackbox-probe.yaml
