crds:
  enabled: true
  upgradeJob:
    enabled: true

defaultRules:
  create: true
  rules:
    windows: false

alertmanager:
  enabled: true
  alertmanagerSpec:
    externalUrl: https://kps-alertmanager.aimhighergg.com

grafana:
  enabled: true
  grafana.ini:
    server:
      root_url: https://kps-grafana.aimhighergg.com

kubeApiServer:
  enabled: true

kubelet:
  enabled: true

kubeControllerManager:
  enabled: true

coreDns:
  enabled: true

kubeDns:
  enabled: false

kubeEtcd:
  enabled: true

kubeScheduler:
  enabled: true

kubeProxy:
  enabled: true

kubeStateMetrics:
  enabled: true
  customResourceState:
    enabled: true
    config:
      spec:
        resources:
          - groupVersionKind:
              group: longhorn.io
              kind: Backup
              version: v1beta2
            metricNamePrefix: kube_custom_resouce_longhorn
            metrics:
              - name: backup_state_condition
                help: Longhorn backup state condition
                labelsFromPath:
                  backup_id: [metadata, name]
                  volume_name: [status, volumeName]
                  snapshot_name: [status, snapshotName]
                each:
                  type: StateSet
                  stateSet:
                    path: [status, state]
                    labelName: state
                    list: ["InProgress", "Completed", "Error", "Unknown"]
          - groupVersionKind:
              group: argoproj.io
              kind: Application
              version: v1alpha1
            metricNamePrefix: kube_custom_resouce_argocd
            metrics:
              - name: application_state
                help: ArgoCD application state
                labelsFromPath:
                  app_name: [metadata, name]
                  namespace: [metadata, namespace]
                each:
                  type: StateSet
                  stateSet:
                    path: [status, health, status]
                    labelName: state
                    list: ["Healthy", "Degraded", "Progressing", "Suspended", "Missing", "Unknown"]
  rbac:
    extraRules:
      - apiGroups:
          - longhorn.io
        resources:
          - backups
        verbs:
          - list
          - watch
      - apiGroups:
          - argoproj.io
        resources:
          - applications
        verbs:
          - list
          - watch

nodeExporter:
  enabled: false

prometheusOperator:
  enabled: true

prometheus:
  enabled: true
  prometheusSpec:
    externalUrl: https://kps-prometheus.aimhighergg.com

thanosRuler:
  enabled: true
  thanosRulerSpec:
    externalPrefix: https://kps-thanos-ruler.aimhighergg.com
