apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
#- ../base/workflow
#- ../base/ci-cd
- ../base/management
#- ../base/observability
#- ../base/security
#- ../base/server
#- ../base/service-mesh
- ../base/service-proxy
#- ../base/storage
#- ../base/webapp

patches:
- target:
    kind: Application
    group: argoproj.io
    version: v1alpha1
    namespace: argocd
    name: app-of-apps-automation
  patch: |-
    - op: replace
      path: /spec/source/path
      value: "application/testing/automation"
    - op: replace
      path: /spec/source/targetRevision
      value: "HEAD"
- target:
    kind: Application
    group: argoproj.io
    version: v1alpha1
    namespace: argocd
    name: app-of-apps-workflow
  patch: |-
    - op: replace
      path: /spec/source/path
      value: "application/testing/workflow"
    - op: replace
      path: /spec/source/targetRevision
      value: "HEAD"
- target:
    kind: Application
    group: argoproj.io
    version: v1alpha1
    namespace: argocd
    name: app-of-apps-ci-cd
  patch: |-
    - op: replace
      path: /spec/source/path
      value: "application/testing/ci-cd"
    - op: replace
      path: /spec/source/targetRevision
      value: "HEAD"
- target:
    kind: Application
    group: argoproj.io
    version: v1alpha1
    namespace: argocd
    name: app-of-apps-management
  patch: |-
    - op: replace
      path: /spec/source/path
      value: "application/testing/management"
    - op: replace
      path: /spec/source/targetRevision
      value: "HEAD"
- target:
    kind: Application
    group: argoproj.io
    version: v1alpha1
    namespace: argocd
    name: app-of-apps-observability
  patch: |-
    - op: replace
      path: /spec/source/path
      value: "application/testing/observability"
    - op: replace
      path: /spec/source/targetRevision
      value: "HEAD"
- target:
    kind: Application
    group: argoproj.io
    version: v1alpha1
    namespace: argocd
    name: app-of-apps-security
  patch: |-
    - op: replace
      path: /spec/source/path
      value: "application/testing/security"
    - op: replace
      path: /spec/source/targetRevision
      value: "HEAD"
- target:
    kind: Application
    group: argoproj.io
    version: v1alpha1
    namespace: argocd
    name: app-of-apps-server
  patch: |-
    - op: replace
      path: /spec/source/path
      value: "application/testing/server"
    - op: replace
      path: /spec/source/targetRevision
      value: "HEAD"
- target:
    kind: Application
    group: argoproj.io
    version: v1alpha1
    namespace: argocd
    name: app-of-apps-service-mesh
  patch: |-
    - op: replace
      path: /spec/source/path
      value: "application/testing/service-mesh"
    - op: replace
      path: /spec/source/targetRevision
      value: "HEAD"
- target:
    kind: Application
    group: argoproj.io
    version: v1alpha1
    namespace: argocd
    name: app-of-apps-service-proxy
  patch: |-
    - op: replace
      path: /spec/source/path
      value: "application/testing/service-proxy"
    - op: replace
      path: /spec/source/targetRevision
      value: "HEAD"
- target:
    kind: Application
    group: argoproj.io
    version: v1alpha1
    namespace: argocd
    name: app-of-apps-storage
  patch: |-
    - op: replace
      path: /spec/source/path
      value: "application/testing/storage"
    - op: replace
      path: /spec/source/targetRevision
      value: "HEAD"
- target:
    kind: Application
    group: argoproj.io
    version: v1alpha1
    namespace: argocd
    name: app-of-apps-webapp
  patch: |-
    - op: replace
      path: /spec/source/path
      value: "application/testing/webapp"
    - op: replace
      path: /spec/source/targetRevision
      value: "HEAD"
- target:
    kind: Application
    group: argoproj.io
    version: v1alpha1
    namespace: argocd
    name: app-of-apps-secret
  patch: |-
    - op: replace
      path: /spec/source/path
      value: "secret/repo/testing"
    - op: replace
      path: /spec/source/targetRevision
      value: "HEAD"
