apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-proxy
  namespace: argocd
spec:
  project: default
  destination:
    server: "https://kubernetes.default.svc"
    namespace: nginx-proxy
  source:
    repoURL: https://github.com/AbeYuki/nginx-proxy-k8s.git
    targetRevision: HEAD
    path: OVERLAYS
    plugin:
      name: kustomize-helmcharts
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
    - CreateNamespace=true


