apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
#- ../../base/ci-cd/argo-rollouts
- ../../base/ci-cd/actions-runnser-controller

patches:
- target:
    kind: Application
    group: argoproj.io
    version: v1alpha1
    namespace: argocd
    name: actions-runner-controller
  patch: |-
    - op: replace
      path: /spec/source/path
      value: "actions-runner-controller/production"
    - op: replace
      path: /spec/source/targetRevision
      value: "HEAD"