apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: maintenance
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/AbeYuki/maintenance-k8s.git
    targetRevision: HEAD
    path: ./
  destination:
    server: https://kubernetes.default.svc
    namespace: maintenance
  syncPolicy:
    syncOptions:
    - CreateNamespace=true