apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nextcloud
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/AbeYuki/nextcloud-k8s.git
    targetRevision: HEAD
    path: overlay/production/
  destination:
    server: https://kubernetes.default.svc
    namespace: nextcloud-production
  syncPolicy:
    syncOptions:
    - CreateNamespace=true