apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nextcloud.fullname" . }}-cron
  labels:
    {{- include "nextcloud.labelsWithComponent" (dict "component" "cron" "context" .) | nindent 4 }}
spec:
  replicas: {{ .Values.cron.replicaCount }}
  selector:
    matchLabels:
      {{- include "nextcloud.selectorLabelsWithComponent" (dict "component" "cron" "context" .) | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/secret: {{ include (print $.Template.BasePath "/nextcloud-secret.yaml") . | sha256sum }}
        {{- with .Values.nextcloud.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "nextcloud.labelsWithComponent" (dict "component" "cron" "context" .) | nindent 8 }}
        {{- with .Values.cron.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.cron.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "nextcloud.serviceAccountName" . }}
      {{- with .Values.cron.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}-cron
          {{- with .Values.cron.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.nextcloud.image.repository }}:{{ .Values.nextcloud.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.nextcloud.image.pullPolicy }}
          command: ["/bin/sh", "-c", "/cron.sh"]
          {{- with .Values.cron.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.cron.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.cron.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: nextcloud
              mountPath: /var/www/html
            {{- if .Values.nextcloud.persistence.data.enabled }}
            - name: nextcloud-data
              mountPath: /var/lib/nextcloud
            {{- end }}
          {{- if .Values.nextcloud.persistence.data.enabled }}
          env:
            - name: NEXTCLOUD_DATA_DIR
              value: "/var/lib/nextcloud/data"
          {{- end }}
          envFrom:
            - secretRef:
                name: {{ include "nextcloud.fullname" . }}-nextcloud
      volumes:
        - name: nextcloud
          persistentVolumeClaim:
            claimName: {{ include "nextcloud.fullname" . }}-nextcloud
        {{- if .Values.nextcloud.persistence.data.enabled }}
        - name: nextcloud-data
          persistentVolumeClaim:
            claimName: {{ .Values.nextcloud.persistence.data.existingClaim | default (printf "%s-nextcloud-data" (include "nextcloud.fullname" .)) }}
        {{- end }}
      {{- with .Values.cron.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.cron.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.cron.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
