apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: {{ include "nextcloud.fullname" . }}-db
    labels:
      {{- include "nextcloud.pvcLabels" . | nindent 4 }}
      app.kubernetes.io/component: db
spec:
  storageClassName: {{ required "db.persistentVolumeClaim.storageClassName is required!" .Values.db.persistentVolumeClaim.storageClassName }}
  accessModes:
    {{- range .Values.db.persistentVolumeClaim.accessModes }}
    - {{ . }}
    {{- end }}
  resources:
    requests:
      storage: {{ required "db.persistentVolumeClaim.size is required!" .Values.db.persistentVolumeClaim.size }}
