apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nextcloud.fullname" . }}-db
  labels:
    {{- include "nextcloud.labelsWithComponent" (dict "component" "nextcloud" "context" .) | nindent 4 }}
type: Opaque
stringData:
{{- range $key, $val := .Values.db.secret }}
  {{ $key }}: {{ $val | quote }}
{{- end }}
