apiVersion: v1
kind: Service
metadata:
  name: {{ include "nextcloud.fullname" . }}-db
  labels:
    {{- include "nextcloud.labelsWithComponent" (dict "component" "db" "context" .) | nindent 4 }}
spec:
  type: {{ .Values.db.service.type }}
  ports:
    - port: {{ .Values.db.service.port }}
      targetPort: {{ .Values.db.service.port }}
      protocol: TCP
  selector:
    {{- include "nextcloud.selectorLabelsWithComponent" (dict "component" "db" "context" .) | nindent 4 }}
