{{- if and .Values.nextcloud.persistence.enabled (not .Values.nextcloud.persistence.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "nextcloud.fullname" . }}-nextcloud
  labels:
    {{- include "nextcloud.pvcLabels" . | nindent 4 }}
    app.kubernetes.io/component: nextcloud
spec:
  accessModes:
    {{- toYaml .Values.nextcloud.persistence.accessModes | nindent 4 }}
  {{- with .Values.nextcloud.persistence.storageClass }}
  storageClassName: {{ . | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.nextcloud.persistence.size }}
{{- end }}
