apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nextcloud.fullname" . }}-nextcloud
  labels:
    {{- include "nextcloud.labelsWithComponent" (dict "component" "nextcloud" "context" .) | nindent 4 }}
type: Opaque
stringData:
{{- $secretKeys := keys .Values.nextcloud.secret | sortAlpha }}
{{- range $key := $secretKeys }}
  {{ $key }}: {{ index $.Values.nextcloud.secret $key | quote }}
{{- end }}
  MYSQL_HOST: {{ printf "%s-db:3306" (include "nextcloud.fullname" .) | quote }}
  REDIS_HOST: {{ printf "%s-redis" (include "nextcloud.fullname" .) | quote }}
