apiVersion: v1
kind: Secret
metadata:
  name: keycloak-credentials
  namespace: keycloak-dev
type: Opaque
stringData:
  KC_BOOTSTRAP_ADMIN_USERNAME: <path:secrets/data/keycloak/admin#username>
  KC_BOOTSTRAP_ADMIN_PASSWORD: <path:secrets/data/keycloak/admin#password>
  GOOGLE_CLIENT_ID: <path:secrets/data/oauth-client/google/keycloak-dev#client_id>
  GOOGLE_CLIENT_SECRET: <path:secrets/data/oauth-client/google/keycloak-dev#client_secret>
