apiVersion: v1
kind: Secret
metadata:
  name: keycloak-database-credentials
  namespace: keycloak-dev
  labels:
    cnpg.io/reload: "true"
type: kubernetes.io/basic-auth
stringData:
  username: <path:secret/data/keycloak-dev/database#username>
  password: <path:secret/data/keycloak-dev/database#password>
