apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base/service-mesh/consul

patches:
- target:
    kind: Application
    group: argoproj.io
    version: v1alpha1
    namespace: argocd
    name: consul
  patch: |-
    - op: replace
      path: /spec/source/path
      value: "consul/production"
    - op: replace
      path: /spec/source/targetRevision
      value: "HEAD"
