apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: haproxy
  namespace: argocd
spec:
  project: default
  destination:
    server: "https://kubernetes.default.svc"
    namespace: haproxy
  source:
    repoURL: https://github.com/AbeYuki/haproxy-k8s.git
    targetRevision: HEAD
    path: OVERLAYS
    plugin:
      name: kustomize-helmcharts
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
    - CreateNamespace=true


