apiVersion: v1
kind: Secret
metadata:
  name: keycloak-credentials
  namespace: keycloak
type: Opaque
stringData:
  password: <path:secret/data/keycloak/database#password>
  KC_BOOTSTRAP_ADMIN_USERNAME: <path:secret/data/keycloak/admin#username>
  KC_BOOTSTRAP_ADMIN_PASSWORD: <path:secret/data/keycloak/admin#password>
  GOOGLE_CLIENT_ID: <path:secret/data/oauth_client/google/keycloak#client_id>
  GOOGLE_CLIENT_SECRET: <path:secret/data/oauth_client/google/keycloak#client_secret>
