apiVersion: v1
kind: Secret
metadata:
  name: {{ include "immich.serverConfigName" . }}
  labels:
    {{- include "immich.labelsWithComponent" (dict "component" "server" "context" .) | nindent 4 }}
  {{- with .Values.server.secret.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
stringData:
{{- range $key, $val := .Values.server.secret.stringData }}
  {{ $key }}: {{ $val | quote }}
{{- end }}
