apiVersion: v1
kind: Service
metadata:
  name: {{ include "immich.serverWorkloadName" . }}
  labels:
    {{- include "immich.labelsWithComponent" (dict "component" "server" "context" .) | nindent 4 }}
spec:
  type: {{ .Values.server.service.type }}
  selector:
    {{- include "immich.selectorLabelsWithComponent" (dict "component" "server" "context" .) | nindent 4 }}
  ports:
    - protocol: TCP
      port: {{ .Values.server.service.port }}
      targetPort: {{ .Values.server.service.targetPort }}
      {{- if and (eq .Values.server.service.type "NodePort") .Values.server.service.nodePort }}
      nodePort: {{ .Values.server.service.nodePort }}
      {{- end }}
