apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-aggregator
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/AbeYuki/ingress-aggregator.git
    targetRevision: HEAD
    path: production
  destination:
    server: https://kubernetes.default.svc
    namespace: ingress-aggregator
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
