apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: longhorn-local
  annotations:
    storageclass.kubernetes.io/description: Longhorn with one strict-local replica for application-level replicated data
provisioner: driver.longhorn.io
allowVolumeExpansion: true
reclaimPolicy: Delete
volumeBindingMode: Immediate
parameters:
  numberOfReplicas: "1"
  dataLocality: disabled
  fsType: ext4
  fromBackup: ""
  staleReplicaTimeout: "30"
  unmapMarkSnapChainRemoved: ignored
