apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: <path:secret/data/viteful/production/env#VITE_LOCATION_NAME_1>-<path:secret/data/viteful/production/namespace#NAMESPACE>-redirect
  namespace: <path:secret/data/viteful/production/namespace#NAMESPACE>
spec:
  redirectRegex:
    regex: ^https?://([^/]+)/.+教室(/.*)?$
    replacement: https://${1}/
    permanent: true
