vmselect:
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 250m
      memory: 512Mi

vminsert:
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 1Gi

vmstorage:
  resources:
    requests:
      cpu: 250m
      memory: 1Gi
    limits:
      cpu: "1"
      memory: 3Gi
  persistentVolume:
    accessModes:
      - ReadWriteMany
    storageClassName: "nfs-g9-enp5s0-rwx"
