apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: immich
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/AbeYuki/immich-k8s.git
    targetRevision: HEAD
    path: production
  destination:
    server: https://kubernetes.default.svc
    namespace: immich
  syncOptions:
    - RespectIgnoreDifferences=true
  ignoreDifferences:
    - group: apps
      kind: Deployment
      name: immich-immich-ml
      namespace: immich   
      jsonPointers:
        - /spec/replicas
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
