apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base/automation/keda
- ../../base/automation/redmine-create-ticket-webhook

patches:
- target:
    kind: Application
    group: argoproj.io
    version: v1alpha1
    namespace: argocd
    name: keda
  patch: |-
    - op: replace
      path: /spec/source/path
      value: "keda/production"
    - op: replace
      path: /spec/source/targetRevision
      value: "HEAD"
- target:
    kind: Application
    group: argoproj.io
    version: v1alpha1
    namespace: argocd
    name: redmine-create-ticket-webhook
  patch: |-
    - op: replace
      patch: /spec/source/path
      value: "overlay/production/"
    - op: replace
      path: /spec/source/targetRevision
      value: "HEAD"
