apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base/observability/exchangerate-exporter
- ../../base/observability/kube-state-metrics
#- ../../base/observability/kubernetes-dashboard
- ../../base/observability/monitoring
- ../../base/observability/temperature-exporter
- ../../base/observability/victoria-metrics-cluster
- ../../base/observability/victoria-logs-cluster
- ../../base/observability/victoria-metrics-alert
#- ../../base/observability/vector

patches:
- target:
    kind: Application
    group: argoproj.io
    version: v1alpha1
    namespace: argocd
    name: exchangerate-exporter
  patch: |-
    - op: replace
      path: /spec/source/path
      value: "./"
    - op: replace
      path: /spec/source/targetRevision
      value: "HEAD"
- target:
    kind: Application
    group: argoproj.io
    version: v1alpha1
    namespace: argocd
    name: kube-state-metrics
  patch: |-
    - op: replace
      path: /spec/source/path
      value: "kube-state-metrics/production"
    - op: replace
      path: /spec/source/targetRevision
      value: "HEAD"
- target:
    kind: Application
    group: argoproj.io
    version: v1alpha1
    namespace: argocd
    name: monitoring
  patch: |-
    - op: replace
      path: /spec/source/path
      value: "overlay/prod"
    - op: replace
      path: /spec/source/targetRevision
      value: "HEAD"
- target:
    kind: Application
    group: argoproj.io
    version: v1alpha1
    namespace: argocd
    name: temperature-exporter
  patch: |-
    - op: replace
      path: /spec/source/path
      value: "./"
    - op: replace
      path: /spec/source/targetRevision
      value: "HEAD"
- target:
    kind: Application
    group: argoproj.io
    version: v1alpha1
    namespace: argocd
    name: victoria-metrics-cluster
  patch: |-
    - op: replace
      path: /spec/source/path
      value: "victoria-metrics-cluster/production"
    - op: replace
      path: /spec/source/targetRevision
      value: "HEAD"
- target:
    kind: Application
    group: argoproj.io
    version: v1alpha1
    namespace: argocd
    name: victoria-logs-cluster
  patch: |-
    - op: replace
      path: /spec/source/path
      value: "victoria-logs-cluster/production"
    - op: replace
      path: /spec/source/targetRevision
      value: "HEAD"
- target:
    kind: Application
    group: argoproj.io
    version: v1alpha1
    namespace: argocd
    name: victoria-mettrics-alert
  patch: |-
    - op: replace
      path: /spec/source/path
      value: "victoria-mettrics-alert/production"
    - op: replace
      path: /spec/source/targetRevision
      value: "HEAD"
- target:
    kind: Application
    group: argoproj.io
    version: v1alpha1
    namespace: argocd
    name: vector
  patch: |-
    - op: replace
      path: /spec/source/path
      value: "vector/production"
    - op: replace
      path: /spec/source/targetRevision
      value: "HEAD"
