apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kps-alertmanager-aimhighergg-com
  namespace: monitoring
  annotations:
    ingressClassName: traefik
    cert-manager.io/cluster-issuer: letsencrypt-prod-dns01
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.middlewares: monitoring-ip-whitelist@kubernetescrd,monitoring-basic-auth@kubernetescrd
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - kps-alertmanager.aimhighergg.com
      secretName: kps-alertmanager-aimhighergg-com-tls
  rules:
    - host: kps-alertmanager.aimhighergg.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: kube-prometheus-stack-alertmanager
                port:
                  number: 9093
