resources:
  - alertmanager-aimhighergg-com.yaml
  - app_1.yaml
  - app_2.yaml
  - argo-rollouts-aimhighergg-com.yaml
  #- grafana-aimhighergg-com.yaml
  - kps-alertmanager-aimhighergg-com.yaml
  - kps-grafana-aimhighergg-com.yaml
  - kps-prometheus-aimhighergg-com.yaml
  - longhorn-aimhighergg-com.yaml
  - prometheus-aimhighergg-com.yaml
  #- vault-aimhighergg-com.yaml
  - vlalert-aimhighergg-com.yaml
  - vmalert-aimhighergg-com.yaml
