persistence:
  defaultDataLocality: "disabled"
preUpgradeChecker:
  jobEnabled: false
defaultSettings:
  defaultDataLocality: "disabled"
  defaultLonghornStaticStorageClass: "longhorn"
  nodeDownPodDeletionPolicy: "delete-both-statefulset-and-deployment-pod"
  nodeDrainPolicy: "block-if-contains-last-replica"
  replicaReplenishmentWaitInterval: 600
  concurrentReplicaRebuildPerNodeLimit: 1
  offlineReplicaRebuilding: false
  replicaAutoBalance: "disabled"
  engineReplicaTimeout: 15
