apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: arc-runner-terraform-sakura-cloud-dns
  namespace: arc-system
spec:
  replicas: 1
  template:
    spec:
      repository: AbeYuki/terraform-sakura-cloud-dns
      labels:
        - self-hosted
        - kubernetes
        - arm64
      containerMode: kubernetes
      serviceAccountName: arc-runner-sa
      workVolumeClaimTemplate: {}
      env:
        - name: ACTIONS_RUNNER_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: ACTIONS_RUNNER_REQUIRE_JOB_CONTAINER
          value: "true"