apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
#- ../../base/server/jypyterlab
- ../../base/server/minecraft-bedrock-arm64
- ../../base/server/nextcloud
- ../../base/server/redmine
- ../../base/server/immich

patches:
- target:
    kind: Application
    group: argoproj.io
    version: v1alpha1
    namespace: argocd
    name: nextcloud
  patch: |-
    - op: replace
      path: /spec/source/path
      value: "overlay/production"
    - op: replace
      path: /spec/source/targetRevision
      value: "HEAD"
- target:
    kind: Application
    group: argoproj.io
    version: v1alpha1
    namespace: argocd
    name: redmine
  patch: |-
    - op: replace
      path: /spec/source/path
      value: "overlay/prod"
    - op: replace
      path: /spec/source/targetRevision
      value: "HEAD"
- target:
    kind: Application
    group: argoproj.io
    version: v1alpha1
    namespace: argocd
    name: immich
  patch: |-
    - op: replace
      path: /spec/source/path
      value: "production"
    - op: replace
      path: /spec/source/targetRevision
      value: "HEAD"
