db:
  persistentVolumeClaim:
    storageClassName: longhorn
    accessModes:
      - ReadWriteMany
    size: 1Gi
nextcloud:
  persistentVolumeClaim:
    storageClassName: longhorn
    accessModes:
      - ReadWriteMany
    size: 1Gi
