db:
  persistentVolumeClaim:
    storageClassName: longhorn
    accessModes:
      - ReadWriteMany
    size: 1Gi
nextcloud:
  persistence:
    storageClass: "longhorn"
    accessModes:
      - ReadWriteMany
    size: 3Gi
    data:
      enabled: true
      storageClass: "nfs-g9-enp4s0-rwx"
      accessModes:
        - ReadWriteMany
      size: 5Gi
