apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base/storage/longhorn
#- ../../base/storage/nfs-provisioner
- ../../base/storage/storageclass

patches:
- target:
    kind: Application
    group: argoproj.io
    version: v1alpha1
    namespace: argocd
    name: longhorn
  patch: |-
    - op: replace
      patch: /spec/source/path
      value: "longhorn/staging"
    - op: replace
      path: /spec/source/targetRevision
      value: "HEAD"
- target:
    kind: Application
    group: argoproj.io
    version: v1alpha1
    namespace: argocd
    name: nfs-provisioner
  patch: |-
    - op: replace
      patch: /spec/source/path
      value: "nfs-subdir-external-provisioner/staging"
    - op: replace
      path: /spec/source/targetRevision
      value: "HEAD"
- target:
    kind: Application
    group: argoproj.io
    version: v1alpha1
    namespace: argocd
    name: storageclass
  patch: |-
    - op: replace
      patch: /spec/source/path
      value: "./"
    - op: replace
      path: /spec/source/targetRevision
      value: "HEAD"
