apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: <path:secret/data/github/private-namespace#<path:secret/data/github/private-namespace#REPO_NAMESPACE_1>
  namespace: argocd
spec:
  project: default
  source:
    repoURL: <path:secret/data/github/private-namespace#<path:secret/data/github/private-repo-url#REPO_URL_1>
    targetRevision: HEAD
    path: overlay/prod-www/
  destination:
    server: https://kubernetes.default.svc
    namespace: <path:secret/data/github/private-namespace#REPO_NAMESPACE_1>
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: <path:secret/data/github/private-namespace#REPO_NAMESPACE_2>
  namespace: argocd
spec:
  project: default
  source:
    repoURL: <path:secret/data/github/private-namespace#<path:secret/data/github/private-repo-url#REPO_URL_2>
    targetRevision: HEAD
    path: overlay/prod-sekime/
  destination:
    server: https://kubernetes.default.svc
    namespace: <path:secret/data/github/private-namespace#REPO_NAMESPACE_2>
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: <path:secret/data/github/private-namespace#REPO_NAMESPACE_3>
  namespace: argocd
spec:
  project: default
  source:
    repoURL: <path:secret/data/github/private-namespace#<path:secret/data/github/private-repo-url#REPO_URL_3>
    targetRevision: HEAD
    path: overlay/prod-sumire/
  destination:
    server: https://kubernetes.default.svc
    namespace: <path:secret/data/github/private-namespace#REPO_NAMESPACE_3>
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
