apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps-management
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/AbeYuki/argocd-apps
    path: application/production/management
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd
