apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps-service-mesh
  namespace: argocd
spec:
  project: default
  source:
    directory:
      recurse: true
    repoURL: https://github.com/AbeYuki/argocd-apps
    path: application/production/service-mesh
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd