apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redmine-create-ticket-webhook
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/AbeYuki/redmine-create-ticket-webhook-k8s.git
    targetRevision: HEAD
    path: OVERLAYS
  destination:
    server: https://kubernetes.default.svc
    namespace: webhook
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true