apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base/webapp/aimhighergg-com
#- ../../base/webapp/maintenance

patches:
- target:
    kind: Application
    group: argoproj.io
    version: v1alpha1
    namespace: argocd
    name: www-aimhighergg-com
  patch: |-
    - op: replace
      path: /spec/source/path
      value: "overlay/staging"
    - op: replace
      path: /spec/source/targetRevision
      value: "staging"
- target:
    kind: Application
    group: argoproj.io
    version: v1alpha1
    namespace: argocd
    name: maintenance
  patch: |-
    - op: replace
      path: /spec/source/path
      value: "./"
    - op: replace
      path: /spec/source/targetRevision
      value: "HEAD"