authSecret:
  enabled: true
  create: true
  github_token: <path:secrets/data/github/actions#TOKEN>
  #github_app_id: "<path:secrets/data/github/apps/AbeYuki-arc#APP_ID>"
  #github_app_installation_id: "<path:secrets/data/github/apps/AbeYuki-arc#INSTALLATION_ID>"
  #github_app_private_key: |
  #  <path:secrets/data/github/apps/AbeYuki-arc#PRIVATE_KEY>
