apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: trust-manager
  namespace: argocd
spec:
  project: default
  destination:
    server: "https://kubernetes.default.svc"
    namespace: cert-manager
  source:
    repoURL: https://github.com/AbeYuki/manifest
    targetRevision: HEAD
    path: trust-manager/production
    plugin:
      name: kustomize-helmcharts
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
    - CreateNamespace=true
