apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base/server/jypyterlab
- ../../base/server/minecraft-bedrock-arm64

patches:
- target:
    kind: Application
    group: argoproj.io
    version: v1alpha1
    namespace: argocd
    name: jyperrlab
  patch: |-
    - op: replace
      patch: /spec/source/path
      value: "overlay/testing"
    - op: replace
      path: /spec/source/targetRevision
      value: "HEAD"
- target:
    kind: Application
    group: argoproj.io
    version: v1alpha1
    namespace: argocd
    name: minecraft-bedrock-arm64
  patch: |-
    - op: replace
      patch: /spec/source/path
      value: "overlay/testing"
    - op: replace
      path: /spec/source/targetRevision
      value: "HEAD"
