apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: exchangerate-exporter
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/AbeYuki/exchangerate-exporter-k8s.git
    targetRevision: HEAD
    path: ./
    plugin:
      name: argocd-vault-plugin-kustomize
  destination:
    server: https://kubernetes.default.svc
    namespace: exchangerate-exporter
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
    - CreateNamespace=true
