apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base/automation/keda

patches:
- target:
    kind: Application
    group: argoproj.io
    version: v1alpha1
    namespace: argocd
    name: keda
  patch: |-
    - op: replace
      path: /spec/source/path
      value: "keda/staging"
    - op: replace
      path: /spec/source/targetRevision
      value: "HEAD"
